name: music
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  # NFC + Deep Links (Axis 3)
  nfc_manager: ^3.5.0
  app_links: ^6.4.0

  # Your existing deps
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  flutter_svg: ^2.0.7
  camera: ^0.10.5+2
  google_mlkit_face_detection: ^0.10.0
  image_picker: ^1.1.2
  share_plus: ^7.2.1
  speech_to_text: ^7.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sharebutton_figma.png
    - assets/smallmic_dark.png
    - assets/smallcamera_dark.png